build:
  publish: public
  command: bash build.sh
services:
  - type: static
    name: anyprint-frontend
    publish: public
    staticPublishOptions:
      redirects:
        - source: "/*"
          destination: "/index.html"
          status: 200