build:
  publish: public
  command: bash build.sh
services:
  - type: static
    name: anyprint-frontend
    publish: public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html